# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Copy Sonos Cloud Controller Files To Bundle Directory
    runs-on: [ubuntu-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Make copy of files
        run: |
          cp Apps/SonosCloudApp.groovy Bundles/SonosCloudController/dwinks.SonosCloudController.groovy
          cp Libraries/UtilitiesAndLoggingLibrary.groovy Bundles/SonosCloudController/dwinks.UtilitiesAndLoggingLibrary.groovy
          cp Drivers/Component/SonosCloudGroup.groovy Bundles/SonosCloudController/dwinks.SonosCloudGroup.groovy
          cp Drivers/Component/SonosCloudPlayer.groovy Bundles/SonosCloudController/dwinks.SonosCloudPlayer.groovy

      - name: Zip Bundle
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'SonosCloudController.zip'
          directory: 'Bundles/SonosCloudController'

      - name: Move Bundle to parent directory
        run: |
          mv Bundles/SonosCloudController/SonosCloudController.zip Bundles/SonosCloudController.zip

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
